### ISSUE TITLE
incomplete mock generation

### ISSUE THREAD

**Issue by cawolf** [cawolf/phpstorm-quick-mock#30]
In some cases, the mock generation fails and creates code fragments like
`$this->config = $this->prophesize(array::`

In the background, an exception is thrown:
```
ERROR: The method designed for fully qualified names only. Got "array|string[]".
java.lang.Throwable: The method designed for fully qualified names only. Got "array|string[]".
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.jetbrains.php.util.PhpContractUtil.assertFqn(PhpContractUtil.java:19)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.isSameNamespace(PhpCodeInsightUtil.java:662)
	at com.jetbrains.php.codeInsight.PhpCodeInsightUtil.alreadyImported(PhpCodeInsightUtil.java:841)
	at de.cawolf.quickmock.intention.service.AddMissingUseStatements.invoke(AddMissingUseStatements.kt:13)
	at de.cawolf.quickmock.intention.QuickMockCreator.invoke(QuickMockCreator.kt:71)
```

**Comment by cawolf** [comment]
Actual example:
```php
<?php

use App\Gitlab\Model\GitlabMapping;
use Http\Client\HttpClient;
use JMS\Serializer\SerializerInterface;

class SubjectUnderTest
{
    private $gitlabClient;
    private $serializer;
    private $mapper;
    private $jiraConfig;

    /**
     * @param string[] $jiraConfig
     */
    public function __construct(HttpClient $gitlabClient, SerializerInterface $serializer, GitlabMapping $mapper, array $jiraConfig)
    {
        $this->gitlabClient = $gitlabClient;
        $this->serializer = $serializer;
        $this->mapper = $mapper;
        $this->jiraConfig = $jiraConfig;
    }
}

```

**Comment by cawolf** [comment]
Ah, I see. IntelliJ interpretes the added DocBlock and the resulting type is not `array`, but `array|string[]`. This then is not part of my primitives list, and treated as an object type.

Solution will probably be to discard terms like `primitive[]` in favor of `array`. I don't think we should go into mixed types like `string|int` in DocBlocks as they are bad practice anyways.
